### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by Alexandria** [Alexandria/match-three-game#41]
We need some basic javascript linter rules set up.

**Comment by W01fw00d** [comment]
Hi! I would like to work on this task and produce a PR if that's ok with you.

We can use [ESlint](https://eslint.org/) which is commonly used in js projects.

Also, here's an idea for creating an additional issue (after this one is solved): using [husky](https://github.com/typicode/husky) to create a pre-commit hook in order to apply those style rules when a maintainer is committing.

**Comment by Alexandria** [comment]
ESlint would be great! And great idea to about adding husky. At this point with the additional contributors something like this is practically necessary at this point. I'll create that issue if it has not been done already.
